/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignedOutRouteImport } from './routes/signed-out'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SsoLoginRouteImport } from './routes/sso.login'
import { Route as SsoCallbackRouteImport } from './routes/sso.callback'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSpacesRouteImport } from './routes/_authenticated/spaces'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedEverythingRouteImport } from './routes/_authenticated/everything'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardsRouteImport } from './routes/_authenticated/dashboards'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedArchivedSpacesRouteImport } from './routes/_authenticated/archived-spaces'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedDashboardsIndexRouteImport } from './routes/_authenticated/dashboards.index'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth.google-calendar.return'
import { Route as AuthenticatedTaskTaskIdRouteImport } from './routes/_authenticated/task.$taskId'
import { Route as AuthenticatedSpaceSpaceIdRouteImport } from './routes/_authenticated/space.$spaceId'
import { Route as AuthenticatedListListIdRouteImport } from './routes/_authenticated/list.$listId'
import { Route as AuthenticatedFolderFolderIdRouteImport } from './routes/_authenticated/folder.$folderId'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedDashboardsIdRouteImport } from './routes/_authenticated/dashboards.$id'
import { Route as ApiPublicGoogleCalendarWebhookRouteImport } from './routes/api/public/google-calendar/webhook'

const SignedOutRoute = SignedOutRouteImport.update({
  id: '/signed-out',
  path: '/signed-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SsoLoginRoute = SsoLoginRouteImport.update({
  id: '/sso/login',
  path: '/sso/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso/callback',
  path: '/sso/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpacesRoute = AuthenticatedSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEverythingRoute = AuthenticatedEverythingRouteImport.update({
  id: '/everything',
  path: '/everything',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardsRoute = AuthenticatedDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchivedSpacesRoute =
  AuthenticatedArchivedSpacesRouteImport.update({
    id: '/archived-spaces',
    path: '/archived-spaces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedDashboardsIndexRoute =
  AuthenticatedDashboardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardsRoute,
  } as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTaskTaskIdRoute = AuthenticatedTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpaceSpaceIdRoute =
  AuthenticatedSpaceSpaceIdRouteImport.update({
    id: '/space/$spaceId',
    path: '/space/$spaceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListListIdRoute = AuthenticatedListListIdRouteImport.update({
  id: '/list/$listId',
  path: '/list/$listId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFolderFolderIdRoute =
  AuthenticatedFolderFolderIdRouteImport.update({
    id: '/folder/$folderId',
    path: '/folder/$folderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedDashboardsIdRoute =
  AuthenticatedDashboardsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardsRoute,
  } as any)
const ApiPublicGoogleCalendarWebhookRoute =
  ApiPublicGoogleCalendarWebhookRouteImport.update({
    id: '/api/public/google-calendar/webhook',
    path: '/api/public/google-calendar/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/signed-out': typeof SignedOutRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/archived-spaces': typeof AuthenticatedArchivedSpacesRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboards': typeof AuthenticatedDashboardsRouteWithChildren
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/everything': typeof AuthenticatedEverythingRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spaces': typeof AuthenticatedSpacesRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/sso/login': typeof SsoLoginRoute
  '/dashboards/$id': typeof AuthenticatedDashboardsIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/folder/$folderId': typeof AuthenticatedFolderFolderIdRoute
  '/list/$listId': typeof AuthenticatedListListIdRoute
  '/space/$spaceId': typeof AuthenticatedSpaceSpaceIdRoute
  '/task/$taskId': typeof AuthenticatedTaskTaskIdRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/dashboards/': typeof AuthenticatedDashboardsIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/api/public/google-calendar/webhook': typeof ApiPublicGoogleCalendarWebhookRoute
}
export interface FileRoutesByTo {
  '/signed-out': typeof SignedOutRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/archived-spaces': typeof AuthenticatedArchivedSpacesRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/everything': typeof AuthenticatedEverythingRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/spaces': typeof AuthenticatedSpacesRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/sso/login': typeof SsoLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboards/$id': typeof AuthenticatedDashboardsIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/folder/$folderId': typeof AuthenticatedFolderFolderIdRoute
  '/list/$listId': typeof AuthenticatedListListIdRoute
  '/space/$spaceId': typeof AuthenticatedSpaceSpaceIdRoute
  '/task/$taskId': typeof AuthenticatedTaskTaskIdRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/dashboards': typeof AuthenticatedDashboardsIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/api/public/google-calendar/webhook': typeof ApiPublicGoogleCalendarWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/signed-out': typeof SignedOutRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/archived-spaces': typeof AuthenticatedArchivedSpacesRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboards': typeof AuthenticatedDashboardsRouteWithChildren
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/everything': typeof AuthenticatedEverythingRoute
  '/_authenticated/gestao': typeof AuthenticatedGestaoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/spaces': typeof AuthenticatedSpacesRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/sso/login': typeof SsoLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dashboards/$id': typeof AuthenticatedDashboardsIdRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/folder/$folderId': typeof AuthenticatedFolderFolderIdRoute
  '/_authenticated/list/$listId': typeof AuthenticatedListListIdRoute
  '/_authenticated/space/$spaceId': typeof AuthenticatedSpaceSpaceIdRoute
  '/_authenticated/task/$taskId': typeof AuthenticatedTaskTaskIdRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/_authenticated/dashboards/': typeof AuthenticatedDashboardsIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/api/public/google-calendar/webhook': typeof ApiPublicGoogleCalendarWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signed-out'
    | '/agenda'
    | '/archived-spaces'
    | '/automations'
    | '/chat'
    | '/dashboards'
    | '/documents'
    | '/everything'
    | '/gestao'
    | '/settings'
    | '/spaces'
    | '/teams'
    | '/workspaces'
    | '/sso/callback'
    | '/sso/login'
    | '/dashboards/$id'
    | '/documents/$id'
    | '/folder/$folderId'
    | '/list/$listId'
    | '/space/$spaceId'
    | '/task/$taskId'
    | '/oauth/google-calendar/return'
    | '/dashboards/'
    | '/documents/'
    | '/api/public/google-calendar/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signed-out'
    | '/agenda'
    | '/archived-spaces'
    | '/automations'
    | '/chat'
    | '/everything'
    | '/gestao'
    | '/settings'
    | '/spaces'
    | '/teams'
    | '/workspaces'
    | '/sso/callback'
    | '/sso/login'
    | '/'
    | '/dashboards/$id'
    | '/documents/$id'
    | '/folder/$folderId'
    | '/list/$listId'
    | '/space/$spaceId'
    | '/task/$taskId'
    | '/oauth/google-calendar/return'
    | '/dashboards'
    | '/documents'
    | '/api/public/google-calendar/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/signed-out'
    | '/_authenticated/agenda'
    | '/_authenticated/archived-spaces'
    | '/_authenticated/automations'
    | '/_authenticated/chat'
    | '/_authenticated/dashboards'
    | '/_authenticated/documents'
    | '/_authenticated/everything'
    | '/_authenticated/gestao'
    | '/_authenticated/settings'
    | '/_authenticated/spaces'
    | '/_authenticated/teams'
    | '/_authenticated/workspaces'
    | '/sso/callback'
    | '/sso/login'
    | '/_authenticated/'
    | '/_authenticated/dashboards/$id'
    | '/_authenticated/documents/$id'
    | '/_authenticated/folder/$folderId'
    | '/_authenticated/list/$listId'
    | '/_authenticated/space/$spaceId'
    | '/_authenticated/task/$taskId'
    | '/oauth/google-calendar/return'
    | '/_authenticated/dashboards/'
    | '/_authenticated/documents/'
    | '/api/public/google-calendar/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SignedOutRoute: typeof SignedOutRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  SsoLoginRoute: typeof SsoLoginRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  ApiPublicGoogleCalendarWebhookRoute: typeof ApiPublicGoogleCalendarWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signed-out': {
      id: '/signed-out'
      path: '/signed-out'
      fullPath: '/signed-out'
      preLoaderRoute: typeof SignedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/sso/login': {
      id: '/sso/login'
      path: '/sso/login'
      fullPath: '/sso/login'
      preLoaderRoute: typeof SsoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso/callback': {
      id: '/sso/callback'
      path: '/sso/callback'
      fullPath: '/sso/callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spaces': {
      id: '/_authenticated/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AuthenticatedSpacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/everything': {
      id: '/_authenticated/everything'
      path: '/everything'
      fullPath: '/everything'
      preLoaderRoute: typeof AuthenticatedEverythingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboards': {
      id: '/_authenticated/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AuthenticatedDashboardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archived-spaces': {
      id: '/_authenticated/archived-spaces'
      path: '/archived-spaces'
      fullPath: '/archived-spaces'
      preLoaderRoute: typeof AuthenticatedArchivedSpacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/dashboards/': {
      id: '/_authenticated/dashboards/'
      path: '/'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AuthenticatedDashboardsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardsRoute
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/task/$taskId': {
      id: '/_authenticated/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof AuthenticatedTaskTaskIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/space/$spaceId': {
      id: '/_authenticated/space/$spaceId'
      path: '/space/$spaceId'
      fullPath: '/space/$spaceId'
      preLoaderRoute: typeof AuthenticatedSpaceSpaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/list/$listId': {
      id: '/_authenticated/list/$listId'
      path: '/list/$listId'
      fullPath: '/list/$listId'
      preLoaderRoute: typeof AuthenticatedListListIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/folder/$folderId': {
      id: '/_authenticated/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof AuthenticatedFolderFolderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/dashboards/$id': {
      id: '/_authenticated/dashboards/$id'
      path: '/$id'
      fullPath: '/dashboards/$id'
      preLoaderRoute: typeof AuthenticatedDashboardsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardsRoute
    }
    '/api/public/google-calendar/webhook': {
      id: '/api/public/google-calendar/webhook'
      path: '/api/public/google-calendar/webhook'
      fullPath: '/api/public/google-calendar/webhook'
      preLoaderRoute: typeof ApiPublicGoogleCalendarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardsRouteChildren {
  AuthenticatedDashboardsIdRoute: typeof AuthenticatedDashboardsIdRoute
  AuthenticatedDashboardsIndexRoute: typeof AuthenticatedDashboardsIndexRoute
}

const AuthenticatedDashboardsRouteChildren: AuthenticatedDashboardsRouteChildren =
  {
    AuthenticatedDashboardsIdRoute: AuthenticatedDashboardsIdRoute,
    AuthenticatedDashboardsIndexRoute: AuthenticatedDashboardsIndexRoute,
  }

const AuthenticatedDashboardsRouteWithChildren =
  AuthenticatedDashboardsRoute._addFileChildren(
    AuthenticatedDashboardsRouteChildren,
  )

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
    AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedArchivedSpacesRoute: typeof AuthenticatedArchivedSpacesRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardsRoute: typeof AuthenticatedDashboardsRouteWithChildren
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedEverythingRoute: typeof AuthenticatedEverythingRoute
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpacesRoute: typeof AuthenticatedSpacesRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFolderFolderIdRoute: typeof AuthenticatedFolderFolderIdRoute
  AuthenticatedListListIdRoute: typeof AuthenticatedListListIdRoute
  AuthenticatedSpaceSpaceIdRoute: typeof AuthenticatedSpaceSpaceIdRoute
  AuthenticatedTaskTaskIdRoute: typeof AuthenticatedTaskTaskIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedArchivedSpacesRoute: AuthenticatedArchivedSpacesRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardsRoute: AuthenticatedDashboardsRouteWithChildren,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedEverythingRoute: AuthenticatedEverythingRoute,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpacesRoute: AuthenticatedSpacesRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFolderFolderIdRoute: AuthenticatedFolderFolderIdRoute,
  AuthenticatedListListIdRoute: AuthenticatedListListIdRoute,
  AuthenticatedSpaceSpaceIdRoute: AuthenticatedSpaceSpaceIdRoute,
  AuthenticatedTaskTaskIdRoute: AuthenticatedTaskTaskIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SignedOutRoute: SignedOutRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  SsoLoginRoute: SsoLoginRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  ApiPublicGoogleCalendarWebhookRoute: ApiPublicGoogleCalendarWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
